project:
  type: website
  render:
    - "*.qmd"

website:
  title: "la cuisine à données"
  navbar:
    background: primary
  page-footer:
    left:
      - text: stats
        href: https://plausible.io/data.11d.im/
    right:
      - icon: github
        href: https://github.com/taniki
      - icon: mastodon
        href: https://social.apreslanu.it/@tk
      - icon: twitter
        href: https://twitter.com/taniki
  repo-url: https://github.com/taniki/data
  repo-actions: [issue]

format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    code-line-numbers: true
    fig-responsive: true

execute:
  freeze: auto

comments:
  giscus:
    repo: taniki/data
