project:
  type: website
  render:
    - "*.qmd"
  preview:
    port: 4000

website:
  title: "la cuisine à données"
  navbar:
    background: primary
    right:
      - icon: github
        href: https://github.com/taniki
        aria-label: GitHub
      - icon: mastodon
        href: https://social.apreslanu.it/@tk
        aria-label: Mastodon
        rel: me
  page-footer:
    left: "dernière modification : {{< meta date >}}"
    right:
      - icon: bar-chart-fill
        href: https://plausible.io/data.11d.im/
        aria-label: statistiques d'audience
      - icon: heart-fill
        href: https://quarto.org
        aria-label: merci à quarto
  repo-url: https://github.com/taniki/data
  repo-actions: [issue]

format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    code-line-numbers: true
    fig-responsive: true

execute:
  freeze: auto

comments:
  giscus:
    repo: taniki/data

date: last-modified
date-format: iso
