project:
  type: website
  render:
    - "*.qmd"

website:
  title: "la cuisine à données"
  navbar:
    background: primary
  page-footer:
    right:
      - icon: github
        href: https://github.com/taniki
      - icon: mastodon
        href: https://social.apreslanu.it/@tk
      - icon: twitter
        href: https://twitter.com/taniki

format:
  html:
    toc: true
    code-fold: true
    code-tools: true
    fig-responsive: true

execute:
  freeze: auto

comments:
  giscus:
    repo: taniki/eco.attention
