---
comments: false

listing:
  - id: recettes
    contents: "/recettes/*.qmd"
    type: grid
  - id: foodcourt
    contents: "/foodcourt/**/index.qmd"
    type: grid
  - id: snacks
    contents: "/snacks/*.qmd"
    type: grid
  - id: datasets
    contents: "/datasets/*qmd"
    type: grid

toc: false
---

:::{.grid}
:::{.g-col-8}
:::{.lead}

Salut ! Ici, c'est [la cuisine à données](a-propos.qmd).

On y prépare des analyses et des visualisations, on partage des techniques pour faire de bons plats, on discute des différents ustensils et des ingrédients. L'idée est de donner à voir le travail de la donnée comme une pratique de production de connaissance et d'information.
:::
:::
:::

:::{.callout-important appearance="simple"}

Ce site vient tout juste de commencer. Les permaliens risquent de bouger subtilement. L'écriture se cherche encore. La présence d'un gif "en construction" des années 90 est également en considération.

Tous les feedbacks sont les bienvenues dans [l'espace discussion de github](https://github.com/taniki/data/discussions). 

:::

## les recettes

Des bouts de code et du partage de techniques

:::{#recettes}
:::


## le food court

Les sujets du moment organisés en séries.

:::{#foodcourt}
:::


## snacks

Des petites explorations à grignoter. 

:::{#snacks}
:::

<!--
## til


## chartbook

-->

## ustensils

liste github : https://github.com/stars/taniki/lists/data-cooking-utensils


## le cellier

Des réserves de nourriture pour l'esprit. Des ingrédients sélectionnés et expliqués

:::{#datasets}
:::

### où trouver des jeux de données

github : https://github.com/stars/taniki/lists/data-ingredients

data.gouv.fr

kaggle

data is plural : https://www.data-is-plural.com/
